#!/bin/bash
sudo apt install -y
sudo apt upgrade -y
sudo apt install curl
sudo curl -L "https://github.com/docker/compose/releases/tag/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo docker–compose --version

