version: '3.5'
services:
 grafana:
  image: grafana/grafana
  container_name: grafana
  restart: on-failure
  ports:
    - "3000:3000"
  volumes:
    # Dados persistentes.
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
   - ./srv/docker/grafana/data:/var/lib/grafana
   - /etc/timezone:/etc/timezone:ro 
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.3'
      memory: 256M
